---
Mappings:
- modelMapping:
    sourceModel: item
    targetModel: product
    fieldMapping:
    - targetField: enabled
      default: true
    - targetField: orgId
      default: "ORG001"
    - targetField: productCategory
      default: "DEFAULT"
    - sourceField: classifications.itemFamilyGroup
      targetField: productClass
    - sourceField: itemId.primaryId
      targetField: productId
    - targetField: sourcingClassification
      default: "DC"
    - targetField: status
      default: "Enabled"
    - targetField: uom
      default: "EACH"
    - sourceField: operationalRules.trackingDateCode
      targetField: timeSensitive
      condition:
        options:
        - eq:
            field: operationalRules.trackingDateCode
            value: "E"
    - sourceField: operationalRules.trackingInformation.trackLotNumbers
      targetField: lotTracked
    - targetField: updateUser
      default: "BY-Connect"
    - targetField: trackingLevel
      default: "SKU"
    segmentMapping:
    - targetSegment: description
      fieldMapping:
      - targetField: short
        sourceField: description.value
        ORG001:
          options:
          - eq:
              field: description.descriptionType
              value: "SHORT"
      - sourceField: description.value
        targetField: long
        condition:
          options:
          - eq:
              field: description.descriptionType
              value: "LONG"
    segmentListMapping:
    - targetSegment: prices
      fieldMapping:
      - targetField: type
        default: "UNITPRICE"
      - sourceField: financialInformation.unitRetailPrice.value
        targetField: value
      - sourceField: financialInformation.unitRetailPrice.currencyCode
        targetField: currency
